# Generated by Django 4.0 on 2023-02-01 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BullyingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('text_type', models.CharField(choices=[('age', 'Age'), ('religion', 'Religion'), ('gender', 'Gender'), ('ethnicityandrace', 'Ethnicity And Race')], max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('text_type', models.CharField(choices=[('notcyberbullying', 'Not Cyber bullying'), ('cyberbullying', 'Cyber Bullying')], max_length=255)),
            ],
        ),
    ]
