# Generated by Django 4.0 on 2023-02-01 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_model', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassifyCyberBullying',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('text_type', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='CyberBullyingOrNot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('text_type', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='BullyingData',
        ),
        migrations.DeleteModel(
            name='TrainingData',
        ),
    ]
