# Generated by Django 4.0 on 2023-02-02 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_model', '0002_classifycyberbullying_cyberbullyingornot_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slang', models.TextField()),
                ('word', models.CharField(max_length=255)),
            ],
        ),
    ]
