# Generated by Django 4.0 on 2023-02-02 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_model', '0004_ethnicityandraceglossary'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgeGlossary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=250)),
            ],
        ),
    ]
