# Generated by Django 4.0 on 2023-02-03 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_model', '0008_negation'),
    ]

    operations = [
        migrations.CreateModel(
            name='OffensiveWithSeverity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=250)),
                ('severity', models.IntegerField(max_length=2)),
            ],
        ),
    ]
