# Generated by Django 4.0 on 2023-03-23 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_model', '0009_offensivewithseverity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offensivewithseverity',
            name='severity',
            field=models.IntegerField(),
        ),
    ]
